### ISSUE TITLE
Add CSS editor (and improve code structure)

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/paged-wp#5]
@jonathanbossenger and I have identified these to-dos for when we have funding available to work on this again:

- Include a settings page for the plugin, to render a text area which can save the custom CSS.
- Render a CodeMirror editor in place of the text area.
- Store the CSS on save, and then render the CSS in the template on paged preview.
- Move the plugin code from procedural to a more object orientated approach, to make it easier to manage the different working parts as the plugin functionality grows.

**Comment by jonathanbossenger** [comment]
@arthurattwell sounds good. Feel free to continue the discussion on the original project workroom when you are ready.

**Comment by typometre** [comment]
I just propose a merge from my fork which provide a metabox instead of the hook to include the plugin in admin editor. #6 
It make it work in Gutenberg editor #7 and would be a better foundation to provide more option in the panel.

- Custom Css would be great.
- A style selector/loader with themes provided by www.paged.design would also be useful

**Comment by typometre** [comment]
Just a note in case it could be useful. You could instantiate wordpress code editor directly in a plugin to avoid adding bloat with another codemirror. https://www.ibenic.com/wordpress-code-editor/

**Comment by arthurattwell** [comment]
This has been completed in #10.
